pub mod activity_tracker;
pub mod client;
pub mod hooks;
pub mod lifecycle;
pub mod projects;
pub mod router;
pub mod scheduler;
pub mod server;
pub mod session_tracker;
pub mod shutdown_watcher;
pub mod tools;

pub use activity_tracker::ActivityTracker;
pub use client::{connect_or_start, connect_or_start_at, is_daemon_running};
pub use db::{default_cache_dir, default_config_dir, default_data_dir, default_port};
pub use hooks::{HookError, HookEvent, HookHandler};
pub use lifecycle::{Daemon, DaemonConfig, LifecycleError, is_running};
pub use projects::{ProjectError, ProjectInfo, ProjectRegistry};
pub use router::{Request, Response, Router, RpcError};
pub use scheduler::{Scheduler, SchedulerConfig, spawn_scheduler};
pub use server::{Client, Server, ServerError, ShutdownHandle, default_socket_path};
pub use session_tracker::{SessionId, SessionTracker};
pub use shutdown_watcher::ShutdownWatcher;
pub use tools::ToolHandler;
