#!/usr/bin/env bun

import tailwindcss from '@tailwindcss/postcss';
import autoprefixer from 'autoprefixer';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import postcss from 'postcss';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = join(__dirname, '..');
const WEBUI_DIR = join(ROOT_DIR, 'src/webui');
const OUTPUT_FILE = join(WEBUI_DIR, 'assets.generated.ts');

async function buildClientBundle(): Promise<string> {
  console.log('Building client bundle...');
  const result = await Bun.build({
    entrypoints: [join(WEBUI_DIR, 'client.tsx')],
    target: 'browser',
    minify: true,
    define: {
      'process.env.NODE_ENV': '"production"',
    },
  });

  if (!result.success) {
    console.error('Failed to build client bundle:');
    for (const log of result.logs) {
      console.error(log.message);
    }
    throw new Error('Client bundle build failed');
  }

  const output = result.outputs[0];
  if (!output) {
    throw new Error('No output from build');
  }
  return await output.text();
}

async function buildTailwindCSS(): Promise<string> {
  console.log('Building Tailwind CSS...');
  const globalsPath = join(WEBUI_DIR, 'globals.css');

  const globalsContent = await Bun.file(globalsPath).text();

  const result = await postcss([tailwindcss(), autoprefixer()]).process(globalsContent, {
    from: globalsPath,
    to: 'styles.css',
  });

  return result.css;
}

function escapeForTemplate(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
}

async function main(): Promise<void> {
  console.log('Pre-building WebUI assets...');

  const [clientJs, css] = await Promise.all([buildClientBundle(), buildTailwindCSS()]);

  const generatedCode = `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/prebuild-webui.ts

export const PREBUILT_CLIENT_JS = \`${escapeForTemplate(clientJs)}\`;

export const PREBUILT_CSS = \`${escapeForTemplate(css)}\`;

export const PREBUILT_ASSETS_AVAILABLE = true;
`;

  await Bun.write(OUTPUT_FILE, generatedCode);
  console.log(`Written pre-built assets to ${OUTPUT_FILE}`);
  console.log(`  Client JS: ${(clientJs.length / 1024).toFixed(1)} KB`);
  console.log(`  CSS: ${(css.length / 1024).toFixed(1)} KB`);
}

main().catch(err => {
  console.error('Prebuild failed:', err);
  process.exit(1);
});
